name: quick_router
description: A quick router for people in a hurry...
version: 1.0.1
repository: https://github.com/bandinopla/quick_router

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
